visualization:
  style: waveform
  waveform:
    num_lines: 5
    line_colors:
    - - 255
      - 0
      - 0
    - - 255
      - 165
      - 0
    - - 255
      - 255
      - 0
    - - 0
      - 255
      - 0
    - - 0
      - 0
      - 255
    position: bottom
