visualization:
  style: waveform
  waveform:
    position: bottom
    num_lines: 6
    line_colors:
    - - 255
      - 0
      - 0
    - - 255
      - 127
      - 0
    - - 255
      - 255
      - 0
    - - 0
      - 255
      - 0
    - - 0
      - 0
      - 255
    - - 127
      - 0
      - 255
